src/genome-browser/api/urls.py
from django.conf import settings
from django.conf.urls import include, url  # For django versions before 2.0
from django.urls import include, path  # For django versions from 2.0 and up

from . import views

urlpatterns = [
]

src/genome-browser/frontend/urls.py
from django.urls import path
from . import views

app_name='frontend'
urlpatterns = [
	path('', views.index, name="index")
]

src/genome-browser/seqview/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from frontend import views as frontendViews
from django.urls import include, path, re_path
from rest_framework import routers
from api import views
from django.conf import settings

admin.site.index_template = 'admin/custom_index.html'
admin.autodiscover()

router = routers.DefaultRouter()
router.register(r'seqalignments', views.getSeqalignments, basename='test')
router.register(r'assemblies', views.getAssemblies, basename='assemblies')
#router.register(r'seqalignments', views.getSeqalignmentsViewSet, basename='seqalignments')
router.register(r'higlassfiles', views.getHiGlassFilesViewSet, basename='higlassfiles')
router.register(r'annotations', views.getAnnotations, basename='annotations')
router.register(r'available-chrom-sizes',views.getAvailableChromSizes, basename='available-chrom-sizes')
router.register(r'chrom-sizes',views.ChromSizes, basename='chrom-sizes')
router.register(r'tileset_info',views.TilesetInfo, basename='tileset_info')
router.register(r'tiles',views.Tiles, basename='tiles')
router.register(r'tilesets',views.Tilesets, basename='tilesets')
router.register(r'suggest',views.Suggest, basename='suggest')
router.register(r'posttrack', views.postTrack, basename='posttrack')
router.register(r'register_url', views.RegisterURL, basename='register_url')

urlpatterns = [
	path('api/v1/tracks/<filename>', views.getTrack),
	path('api/v1/tracks/annotations/<filename>', views.getTrack),
	path('api/v1/tracks/annotations/index/<filename>', views.getTrack),	
	path('api/v1/', include(router.urls)),
	path('', include('frontend.urls')),
	path('admin/', admin.site.urls),
	path('upload/', views.adminPage),
	path('accounts/login/', LoginView.as_view(template_name='registration/login.html',), name = 'login'),
	path('accounts/logout/', LogoutView.as_view(template_name='registration/logout.html')),
	re_path(r'^(?:.*)/?$', frontendViews.index)
]

src/genome-browser/templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}">
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}">{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}">
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}">{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE">{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'frontend:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear">
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
{% block footerscripts %}{% endblock %}
</html>

src/genome-browser/templates/base_site.html
{% extends "base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('SeqView') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'frontend:index' %}">{{ site_header|default:_('SeqView') }}</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}